"""Tests for bin/jarvis-upgrade-migrate header parsing."""
from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from importlib.machinery import SourceFileLoader
from pathlib import Path

JARVIS_ROOT = Path(__file__).resolve().parents[1]
MIGRATE = JARVIS_ROOT / "bin" / "jarvis-upgrade-migrate"

_loader = SourceFileLoader("jarvis_upgrade_migrate", str(MIGRATE))
_spec = importlib.util.spec_from_loader("jarvis_upgrade_migrate", _loader)
migrate = importlib.util.module_from_spec(_spec)
sys.modules["jarvis_upgrade_migrate"] = migrate
_loader.exec_module(migrate)


class TestHeaderParsing(unittest.TestCase):
    def test_standard_terraform_header(self):
        with tempfile.NamedTemporaryFile("w", suffix=".tf", delete=False) as f:
            f.write("# Generated by Jarvis v1.0.0 on 2026-06-08\n")
            f.write("# feature:networking template:alb@4aad53d82dbb\n")
            f.write("# Safe to edit.\n\n")
            f.write('resource "aws_lb" "main" { ... }\n')
            path = Path(f.name)
        header = migrate.parse_header(path)
        self.assertIsNotNone(header)
        feature, template, hash_val = header
        self.assertEqual(feature, "networking")
        self.assertEqual(template, "alb")
        self.assertEqual(hash_val, "4aad53d82dbb")
        path.unlink()

    def test_python_file_header(self):
        with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as f:
            f.write('"""Generated by Jarvis v1.0.0.\n')
            f.write("feature:auth template:python.routes@abcd12345678\n")
            f.write('"""\n')
            path = Path(f.name)
        header = migrate.parse_header(path)
        self.assertIsNotNone(header)
        self.assertEqual(header[0], "auth")
        path.unlink()

    def test_file_without_header(self):
        with tempfile.NamedTemporaryFile("w", suffix=".tf", delete=False) as f:
            f.write('resource "aws_lb" "main" { ... }\n')
            path = Path(f.name)
        self.assertIsNone(migrate.parse_header(path))
        path.unlink()


if __name__ == "__main__":
    unittest.main()
